### ISSUE TITLE
doen't work

### ISSUE THREAD

**Issue by ngdream** [sherif-abdallah/Movie-Link#1]
# error message

```
Traceback (most recent call last):
  File "c:\users\pc\appdata\local\programs\python\python38\lib\runpy.py", line 184, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "c:\users\pc\appdata\local\programs\python\python38\lib\runpy.py", line 143, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "c:\users\pc\appdata\local\programs\python\python38\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "A:\code\githubparticipation\movie-scrapper\lib\site-packages\streamlit\__init__.py", line 48, in <module>
    from streamlit.proto.RootContainer_pb2 import RootContainer
  File "A:\code\githubparticipation\movie-scrapper\lib\site-packages\streamlit\proto\RootContainer_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "A:\code\githubparticipation\movie-scrapper\lib\site-packages\google\protobuf\descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by ngdream** [comment]
i use window 10
